add_newline=false
format = "$directory$git_branch$git_status$character "
right_format = "[](fg:bg)$status$cmd_duration$python$nix_shell$custom"
palette = 'lad1337'

[palettes.lad1337]
bg = '#444444'
divider = '#7a7a7a'
error = 'red'
success = '#00dd00'
dir = '#00afff'

[character]
success_symbol = "[](fg:bg)" # ➜ ▶
error_symbol= "[](fg:bg)" # "➜" "▶"
vimcmd_symbol = "[](fg:bg)"

[cmd_duration]
format = "[](fg:divider bg:bg)[ $duration ]($style)"
style = "fg:#9b9b9b bg:bg"

[custom]
[custom.direnv]
format = "[](fg:divider bg:bg)[ $symbol ]($style)"
style = "fg:divider bg:bg"
symbol = "[▼](fg:white bg:bg)"
when = "test \"$DIRENV_WATCHES\" != \"\""

[custom.vim_shell]
format = "[](fg:#7a7a7a bg:bg)[ $symbol ]($style)"
style = "fg:divider bg:bg"
symbol = "[](fg:green bg:bg)"
when = "test \"$VIMRUNTIME\" != \"\""

[directory]
format = "[ $path ]($style)"
style = "fg:dir bg:bg"
truncate_to_repo = false

[git_branch]
format = "[](fg:divider bg:bg)[ $branch(:$remote_branch) ]($style)"
style = "fg:success bg:bg"

[git_metrics]
added_style = "fg:#b4951e bg:bg"
deleted_style = "fg:bright-red bg:235"
disabled = false
format = "([+$added]($added_style))[]($added_style)"

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
format = "[$all_status$ahead_behind ]($style)"
modified = "[!$count ](fg:#b4951e bg:bg)"
style = "fg:#b4951e bg:bg"
untracked = "[?$count ](fg:#00afff bg:bg)"

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[nix_shell]
format = "[](fg:divider bg:bg)[ $state $symbol ]($style)"
style = "fg:#5690ad bg:bg"
symbol = "❄️"

[status]
disabled = false
format = "[ $signal_name $symbol ](bg:bg)"
map_symbol = true
sigint_symbol = "[✘](fg:#d60202 bg:bg)"
success_symbol = "[✔](fg:green bg:bg)"
symbol = "[✘](fg:#d60202 bg:bg)"

