git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  skipDiscardChangeWarning: true
  theme:
    activeBorderColor:
      - "#EDFF00"
      - bold
    inactiveBorderColor:
      - "#565f89"
    optionsTextColor:
      - "#7c3aed"
    selectedLineBgColor:
      - "#900048"
    cherryPickedCommitBgColor:
      - "#900048"
    cherryPickedCommitFgColor:
      - "#2ac3de"
    unstagedChangesColor:
      - "#ff0e82"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#EDFF00"
